# Use the official Apache Spark image
FROM bitnami/spark:3.1.2

# Switch to root to install dependencies
USER root

# Set the working directory
WORKDIR /

# Copy requirements file and install Python dependencies
COPY ./requirements.txt .
RUN pip install --no-cache-dir --timeout=300 -r requirements.txt

# Install OpenJDK 11
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    openjdk-11-jdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set Java environment variables
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

# Copy Spark job code and any other necessary files
COPY ./spark /
COPY ./scheduler /scheduler



# Copy the JDBC connector jar
COPY ./jars/mysql-connector-j-9.3.0.jar /


COPY spark-master-startup.sh /spark-master-startup.sh
RUN chmod +x /spark-master-startup.sh
ENTRYPOINT ["/spark-master-startup.sh"]
