version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports: ["2181:2181"]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: [dari_rec_system_network]

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports: ["9092:9092", "9093:9093"]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on: [zookeeper]
    networks: [dari_rec_system_network]

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports: ["6379:6379"]
    networks: [dari_rec_system_network]

  mysql:
    image: mysql:latest
    container_name: mysqlc
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: dari_db
    ports: ["3306:3306"]
    volumes: [mysqlc-data:/var/lib/mysql]
    networks: [dari_rec_system_network]


  spark-master:
    image: mohamedaminelili02/spark-master:1.0.0
    environment: 
      - SPARK_MODE=master
    ports: ["7077:7077", "8081:8080","5000:5000"]
    networks: [dari_rec_system_network]
    volumes:
      - ./scheduler:/opt/spark/scheduler
      - ./spark:/opt/spark
    depends_on:
      - mysql
      


  spark-worker:
    image: bitnami/spark:3.1.2
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_INSTANCES=1
      - SPARK_MASTER_IP=spark-master

    depends_on: [spark-master]
    networks: [dari_rec_system_network]
  
  dari:
    image: mohamedaminelili02/dari-front:1.0.0
    container_name: frontend
    ports: ["80:80"]
    networks: [dari_rec_system_network]
    environment:
      - API_BASE_URL=http://dari/api
    depends_on:
      - dari-server  
  dari-server:
    image: mohamedaminelili02/dari-server:1.0.0
    container_name: backend
    ports: ["8080:8080"]
    networks: [dari_rec_system_network]
    environment:
      - KAFKA_ENABLED=false
    depends_on:
      - mysql
      - kafka
  scheduler:
    image: mohamedaminelili02/scheduler-app:1.0.0
    container_name: scheduler-app
    ports: ["5001:5001"]
    networks: [dari_rec_system_network]
    depends_on:
      - spark-master
      - mysql


volumes:
  mysqlc-data:

networks:
  dari_rec_system_network:
    driver: bridge