# Define components
agent.sources = kafka-source
agent.sinks = hdfs-sink
agent.channels = memory-channel

# Kafka Source
agent.sources.kafka-source.type = org.apache.flume.source.kafka.KafkaSource
agent.sources.kafka-source.kafka.topics = user-event-topic
agent.sources.kafka-source.kafka.bootstrap.servers = kafka:9093
agent.sources.kafka-source.kafka.consumer.group.id = flume-consumer-group
agent.sources.kafka-source.kafka.consumer.auto.offset.reset = earliest
agent.sources.kafka-source.batchSize = 1000
agent.sources.kafka-source.batchDurationMillis = 2000
agent.sources.kafka-source.channels = memory-channel

# HDFS Sink
agent.sinks.hdfs-sink.type = hdfs
agent.sinks.hdfs-sink.hdfs.path = hdfs://namenode:9870/kafka/data/test
agent.sinks.hdfs-sink.hdfs.filePrefix = events-
agent.sinks.hdfs-sink.hdfs.fileSuffix = .log
agent.sinks.hdfs-sink.hdfs.fileType = DataStream
agent.sinks.hdfs-sink.hdfs.rollInterval = 600
agent.sinks.hdfs-sink.hdfs.rollSize = 0
agent.sinks.hdfs-sink.hdfs.rollCount = 0
agent.sinks.hdfs-sink.hdfs.idleTimeout = 0
agent.sinks.hdfs-sink.serializer = TEXT
agent.sinks.hdfs-sink.serializer.appendNewline = true
agent.sinks.hdfs-sink.channel = memory-channel

# Memory Channel
agent.channels.memory-channel.type = memory
agent.channels.memory-channel.capacity = 100000
agent.channels.memory-channel.transactionCapacity = 10000