spark.master                     spark://spark-master:7077
spark.app.name                   airflow-spark-app
spark.submit.deployMode          client
spark.eventLog.enabled           true
spark.eventLog.dir               file:///tmp/spark-events
spark.executor.memory            1g
spark.driver.memory              1g
spark.driver.extraJavaOptions    -Dlog4j.configuration=file:/opt/spark/conf/log4j.properties
spark.executor.extraJavaOptions  -Dlog4j.configuration=file:/opt/spark/conf/log4j.properties
